#!/usr/bin/with-contenv bash
#shellcheck shell=bash

rtlmuxer --src-address=127.0.0.1 --src-port=1234 --sink-bind-address=0.0.0.0 --sink-bind-port-b=$TCP_PORT 2>&1 | stdbuf -o0 awk '{print "[rtlmuxer] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
